/**
 * macos-insertable native layer — reads and writes the focused text field of macOS applications.
 *
 * The addon exposes primitives only: it reads raw Accessibility attributes, performs a single
 * requested write, posts synthetic events, and snapshots the pasteboard. Every decision — which
 * delivery rung to take, whether a write actually landed, whether a field is sensitive — lives in
 * TypeScript, where it is unit-testable against a fake binding on any operating system.
 *
 * Threading: Accessibility calls message another process and block, so they run on libuv workers
 * with an explicit messaging timeout. NSWorkspace and NSPasteboard are main-thread APIs and stay
 * synchronous. A pasteboard owner can delay a flavor read, so callers must treat snapshot failure
 * as a normal reason to use a non-paste delivery path.
 *
 * Permission: every AX and CGEvent entry point here requires the macOS Accessibility (TCC) grant.
 * Without it the AX calls return kAXErrorAPIDisabled and the event posts are dropped by the
 * window server. `isAccessibilityTrusted` reports the grant so callers can refuse early.
 */

#import <AppKit/AppKit.h>
#import <ApplicationServices/ApplicationServices.h>
#import <Carbon/Carbon.h>
#import <CoreGraphics/CoreGraphics.h>
#import <IOKit/IOKitLib.h>

// A pasteboard snapshot is held across the paste it protects, which spans several run-loop turns.
// Without ARC the stash keeps raw pointers into an autorelease pool that drains in between, and
// restoring one is a use-after-free that kills the process the moment a paste lands. Host
// processes without a running NSRunLoop never drain, so this cannot be caught by a smoke test —
// only the compiler can enforce it.
#if !__has_feature(objc_arc)
#error "insertable.mm must be compiled with ARC (CLANG_ENABLE_OBJC_ARC in binding.gyp)."
#endif

#include <napi.h>

#include <cstdint>
#include <initializer_list>
#include <map>
#include <mutex>
#include <string>
#include <vector>

namespace {

// Virtual keycodes are physical, not character-based, so they hold on any keyboard layout. That
// matters for Command-V specifically: layouts that remap to QWERTY while Command is held resolve
// the *character* "v" to a different physical key.
constexpr CGKeyCode kKeyCodeV = 0x09;
constexpr CGKeyCode kKeyCodeDelete = 0x33;
constexpr CGKeyCode kKeyCodeReturn = 0x24;
constexpr CGKeyCode kKeyCodeCommand = 0x37;
constexpr CGKeyCode kKeyCodeShift = 0x38;

// Passed as the modifier keycode for a keystroke that takes no modifier.
constexpr CGKeyCode kNoModifierKey = 0xFFFF;

// Marker types that ask well-behaved clipboard managers (Maccy, Paste, Raycast, Alfred) not to
// record an item. Text routed through the pasteboard on a caller's behalf is transient by
// definition; delivery must not be what files it into a third-party clipboard history. These are
// conventions published at nspasteboard.org — nothing enforces them, so they reduce the exposure
// rather than removing it.
constexpr const char* kConcealmentTypes[] = {"org.nspasteboard.ConcealedType",
                                             "org.nspasteboard.TransientType",
                                             "org.nspasteboard.AutoGeneratedType"};

// Names the writer, so a clipboard manager honouring the conventions above can attribute the item.
constexpr const char* kPasteboardSourceType = "org.nspasteboard.source";

// CGEventKeyboardSetUnicodeString grows unreliable past roughly this many UTF-16 units per event,
// so typed text is delivered in chunks.
constexpr CFIndex kTypeChunkUnits = 16;

// The typing rung blocks its worker between chunks; a long payload belongs on the paste rung.
constexpr size_t kMaxTypeUnits = 2000;

// Pause between typed chunks. Apps that debounce their own input handling drop characters when
// synthetic events arrive with no gap at all.
constexpr useconds_t kTypeChunkDelayUs = 1200;

// Settle schedule for reads that verify a write. Chromium-backed views accept a write and
// mirror it asynchronously — measured: a selection set reads back stale in the same trip and
// lands ~10ms later — while AppKit answers in-trip. The first retry is sized for Chromium's
// common case so successful verifies cost ~10ms there and 0ms on AppKit.
constexpr useconds_t kMirrorSettleUs[] = {10 * 1000, 35 * 1000, 35 * 1000};
constexpr int kMirrorSettleSteps = 3;

// Total bytes a snapshot may hold. A pasteboard over this is not borrowed at all — keeping a
// 50 MB image alive for the length of a paste is not worth it.
constexpr NSUInteger kMaxSnapshotBytes = 16 * 1024 * 1024;

std::string CFStringToStd(CFStringRef value) {
  if (!value) return "";
  CFIndex length = CFStringGetLength(value);
  if (length == 0) return "";
  CFIndex capacity = CFStringGetMaximumSizeForEncoding(length, kCFStringEncodingUTF8) + 1;
  std::vector<char> buffer(static_cast<size_t>(capacity));
  if (!CFStringGetCString(value, buffer.data(), capacity, kCFStringEncodingUTF8)) return "";
  return std::string(buffer.data());
}

CFStringRef CreateCFString(const std::string& value) {
  return CFStringCreateWithBytes(kCFAllocatorDefault,
                                 reinterpret_cast<const UInt8*>(value.data()),
                                 static_cast<CFIndex>(value.size()), kCFStringEncodingUTF8, false);
}

/**
 * Live AXUIElementRefs held across the gap between capture and delivery, addressed by opaque
 * token. Delivery re-finds the element the user was actually focused in rather than trusting
 * whatever holds focus later.
 */
class ElementRegistry {
 public:
  static ElementRegistry& Shared() {
    static ElementRegistry registry;
    return registry;
  }

  std::string Store(AXUIElementRef element) {
    std::lock_guard<std::mutex> guard(mutex_);
    std::string token = "ax-" + std::to_string(++counter_);
    CFRetain(element);
    elements_[token] = element;
    return token;
  }

  /** Returns a retained reference the caller must CFRelease, or NULL when the token is unknown. */
  AXUIElementRef Copy(const std::string& token) {
    std::lock_guard<std::mutex> guard(mutex_);
    auto found = elements_.find(token);
    if (found == elements_.end()) return NULL;
    CFRetain(found->second);
    return found->second;
  }

  void Release(const std::string& token) {
    std::lock_guard<std::mutex> guard(mutex_);
    auto found = elements_.find(token);
    if (found == elements_.end()) return;
    CFRelease(found->second);
    elements_.erase(found);
  }

 private:
  std::mutex mutex_;
  std::map<std::string, AXUIElementRef> elements_;
  uint64_t counter_ = 0;
};

/**
 * Pasteboard contents copied out of the pasteboard so a later clearContents cannot void them.
 *
 * The stash outlives the call that fills it — a snapshot is held across the paste it protects,
 * which spans several run-loop turns. ARC is what makes the map's Objective-C pointers strong;
 * this file must not be compiled without it (see binding.gyp).
 */
class PasteboardStash {
 public:
  static PasteboardStash& Shared() {
    static PasteboardStash stash;
    return stash;
  }

  std::string Store(NSArray<NSPasteboardItem*>* items) {
    std::lock_guard<std::mutex> guard(mutex_);
    std::string token = "pb-" + std::to_string(++counter_);
    items_[token] = items;
    return token;
  }

  NSArray<NSPasteboardItem*>* Take(const std::string& token) {
    std::lock_guard<std::mutex> guard(mutex_);
    auto found = items_.find(token);
    if (found == items_.end()) return nil;
    NSArray<NSPasteboardItem*>* items = found->second;
    items_.erase(found);
    return items;
  }

 private:
  std::mutex mutex_;
  std::map<std::string, NSArray<NSPasteboardItem*>*> items_;
  uint64_t counter_ = 0;
};

// ── Accessibility attribute readers ─────────────────────────────────────────

bool CopyAxString(AXUIElementRef element, CFStringRef attribute, std::string* out) {
  CFTypeRef value = NULL;
  if (AXUIElementCopyAttributeValue(element, attribute, &value) != kAXErrorSuccess) return false;
  if (!value) return false;
  bool ok = false;
  if (CFGetTypeID(value) == CFStringGetTypeID()) {
    *out = CFStringToStd(static_cast<CFStringRef>(value));
    ok = true;
  }
  CFRelease(value);
  return ok;
}

/** Reads a string attribute, truncating to `maxChars` UTF-16 units. */
bool CopyAxStringCapped(AXUIElementRef element, CFStringRef attribute, CFIndex maxChars,
                        std::string* out) {
  CFTypeRef value = NULL;
  if (AXUIElementCopyAttributeValue(element, attribute, &value) != kAXErrorSuccess) return false;
  if (!value) return false;
  bool ok = false;
  if (CFGetTypeID(value) == CFStringGetTypeID()) {
    CFStringRef text = static_cast<CFStringRef>(value);
    CFIndex length = CFStringGetLength(text);
    if (maxChars > 0 && length > maxChars) {
      CFStringRef head = CFStringCreateWithSubstring(kCFAllocatorDefault, text,
                                                     CFRangeMake(0, maxChars));
      // A cut on a UTF-16 boundary can split a surrogate pair; the TypeScript side runs every
      // captured string through a well-formedness pass before it can be serialized.
      *out = CFStringToStd(head);
      if (head) CFRelease(head);
    } else {
      *out = CFStringToStd(text);
    }
    ok = true;
  }
  CFRelease(value);
  return ok;
}

bool CopyAxRange(AXUIElementRef element, CFStringRef attribute, CFRange* out) {
  CFTypeRef value = NULL;
  if (AXUIElementCopyAttributeValue(element, attribute, &value) != kAXErrorSuccess) return false;
  if (!value) return false;
  bool ok = false;
  if (CFGetTypeID(value) == AXValueGetTypeID() &&
      AXValueGetType(static_cast<AXValueRef>(value)) == kAXValueTypeCFRange) {
    ok = AXValueGetValue(static_cast<AXValueRef>(value), kAXValueTypeCFRange, out);
  }
  CFRelease(value);
  return ok;
}

bool CopyAxLong(AXUIElementRef element, CFStringRef attribute, long* out) {
  CFTypeRef value = NULL;
  if (AXUIElementCopyAttributeValue(element, attribute, &value) != kAXErrorSuccess) return false;
  if (!value) return false;
  bool ok = false;
  if (CFGetTypeID(value) == CFNumberGetTypeID()) {
    ok = CFNumberGetValue(static_cast<CFNumberRef>(value), kCFNumberLongType, out);
  }
  CFRelease(value);
  return ok;
}

bool CopyAxBool(AXUIElementRef element, CFStringRef attribute, bool fallback) {
  CFTypeRef value = NULL;
  if (AXUIElementCopyAttributeValue(element, attribute, &value) != kAXErrorSuccess) return fallback;
  if (!value) return fallback;
  bool result = fallback;
  if (CFGetTypeID(value) == CFBooleanGetTypeID()) {
    result = CFBooleanGetValue(static_cast<CFBooleanRef>(value));
  }
  CFRelease(value);
  return result;
}

bool CopyAxPoint(AXUIElementRef element, CFStringRef attribute, CGPoint* out) {
  CFTypeRef value = NULL;
  if (AXUIElementCopyAttributeValue(element, attribute, &value) != kAXErrorSuccess) return false;
  if (!value) return false;
  bool ok = false;
  if (CFGetTypeID(value) == AXValueGetTypeID() &&
      AXValueGetType(static_cast<AXValueRef>(value)) == kAXValueTypeCGPoint) {
    ok = AXValueGetValue(static_cast<AXValueRef>(value), kAXValueTypeCGPoint, out);
  }
  CFRelease(value);
  return ok;
}

bool CopyAxSize(AXUIElementRef element, CFStringRef attribute, CGSize* out) {
  CFTypeRef value = NULL;
  if (AXUIElementCopyAttributeValue(element, attribute, &value) != kAXErrorSuccess) return false;
  if (!value) return false;
  bool ok = false;
  if (CFGetTypeID(value) == AXValueGetTypeID() &&
      AXValueGetType(static_cast<AXValueRef>(value)) == kAXValueTypeCGSize) {
    ok = AXValueGetValue(static_cast<AXValueRef>(value), kAXValueTypeCGSize, out);
  }
  CFRelease(value);
  return ok;
}

/** Whether `frame` intersects any active display, in CG global (top-left origin) coordinates —
 *  the space kAXPositionAttribute reports in. A raw fact for TypeScript's decoy judgment. */
bool FrameIntersectsAnyDisplay(CGRect frame) {
  CGDirectDisplayID displays[16];
  uint32_t count = 0;
  if (CGGetActiveDisplayList(16, displays, &count) != kCGErrorSuccess) return true;
  for (uint32_t i = 0; i < count; i += 1) {
    if (CGRectIntersectsRect(CGDisplayBounds(displays[i]), frame)) return true;
  }
  return count == 0;
}

bool IsAttributeSettable(AXUIElementRef element, CFStringRef attribute) {
  Boolean settable = false;
  if (AXUIElementIsAttributeSettable(element, attribute, &settable) != kAXErrorSuccess) return false;
  return settable ? true : false;
}

/**
 * Every attribute the element advertises. This is what lets text capability be *detected* rather
 * than guessed from a list of known roles: an element that carries AXValue and AXSelectedTextRange
 * behaves like a text box no matter what an application chose to call it.
 */
std::vector<std::string> CopyAttributeNames(AXUIElementRef element) {
  std::vector<std::string> names;
  CFArrayRef attributes = NULL;
  if (AXUIElementCopyAttributeNames(element, &attributes) != kAXErrorSuccess) return names;
  if (!attributes) return names;
  CFIndex count = CFArrayGetCount(attributes);
  names.reserve(static_cast<size_t>(count));
  for (CFIndex i = 0; i < count; i += 1) {
    CFTypeRef entry = CFArrayGetValueAtIndex(attributes, i);
    if (entry && CFGetTypeID(entry) == CFStringGetTypeID()) {
      names.push_back(CFStringToStd(static_cast<CFStringRef>(entry)));
    }
  }
  CFRelease(attributes);
  return names;
}

/** Mutable text state, read back immediately after a write so TypeScript can verify it landed. */
struct TextState {
  bool hasValue = false;
  std::string value;
  std::string selectedText;
  bool hasSelection = false;
  long selectionStart = 0;
  long selectionLength = 0;
  long numberOfCharacters = -1;
};

void ReadTextState(AXUIElementRef element, CFIndex valueMaxChars, TextState* state) {
  state->hasValue = CopyAxStringCapped(element, kAXValueAttribute, valueMaxChars, &state->value);
  CopyAxString(element, kAXSelectedTextAttribute, &state->selectedText);
  CFRange range = CFRangeMake(0, 0);
  if (CopyAxRange(element, kAXSelectedTextRangeAttribute, &range)) {
    state->hasSelection = true;
    state->selectionStart = static_cast<long>(range.location);
    state->selectionLength = static_cast<long>(range.length);
  }
  CopyAxLong(element, kAXNumberOfCharactersAttribute, &state->numberOfCharacters);
}

Napi::Object TextStateToObject(Napi::Env env, const TextState& state) {
  Napi::Object object = Napi::Object::New(env);
  object.Set("hasValue", Napi::Boolean::New(env, state.hasValue));
  object.Set("value", Napi::String::New(env, state.value));
  object.Set("selectedText", Napi::String::New(env, state.selectedText));
  if (state.hasSelection) {
    object.Set("selectionStart", Napi::Number::New(env, static_cast<double>(state.selectionStart)));
    object.Set("selectionLength",
               Napi::Number::New(env, static_cast<double>(state.selectionLength)));
  } else {
    object.Set("selectionStart", env.Null());
    object.Set("selectionLength", env.Null());
  }
  object.Set("numberOfCharacters",
             Napi::Number::New(env, static_cast<double>(state.numberOfCharacters)));
  return object;
}

/** Attributes identifying an element well enough to refuse writing into a different one. */
struct ElementIdentity {
  std::string role;
  std::string subrole;
  std::string title;
  std::string description;
  std::string placeholder;
  std::string identifier;
};

void ReadIdentity(AXUIElementRef element, ElementIdentity* identity) {
  CopyAxString(element, kAXRoleAttribute, &identity->role);
  CopyAxString(element, kAXSubroleAttribute, &identity->subrole);
  CopyAxString(element, kAXTitleAttribute, &identity->title);
  CopyAxString(element, kAXDescriptionAttribute, &identity->description);
  CopyAxString(element, CFSTR("AXPlaceholderValue"), &identity->placeholder);
  CopyAxString(element, CFSTR("AXIdentifier"), &identity->identifier);
}

void AssignIdentity(Napi::Object object, const ElementIdentity& identity) {
  Napi::Env env = object.Env();
  object.Set("role", Napi::String::New(env, identity.role));
  object.Set("subrole", Napi::String::New(env, identity.subrole));
  object.Set("title", Napi::String::New(env, identity.title));
  object.Set("description", Napi::String::New(env, identity.description));
  object.Set("placeholder", Napi::String::New(env, identity.placeholder));
  object.Set("identifier", Napi::String::New(env, identity.identifier));
}

/** Applies the messaging timeout that keeps a wedged target app from blocking a libuv worker. */
void ApplyTimeout(AXUIElementRef element, double timeoutMs) {
  AXUIElementSetMessagingTimeout(element, static_cast<float>(timeoutMs / 1000.0));
}

/**
 * The pid owning the frontmost ordinary window, straight from the window server, or -1.
 *
 * Deliberately NOT NSWorkspace's frontmostApplication and NOT the system-wide accessibility
 * element's focused application: both are notification-fed caches that need a serviced run
 * loop, and in a plain Node process (no NSRunLoop) both freeze at their first answer forever,
 * silently — measured, including the AX one. The window list is a fresh window-server round
 * trip on every call. Layer 0 filters to ordinary application windows; the list is ordered
 * front to back, so the first hit is the window under the user's keys. Window OWNERSHIP is
 * plain metadata, readable without the Screen Recording permission that window NAMES need.
 */
pid_t FocusedAppPid() {
  CFArrayRef windows = CGWindowListCopyWindowInfo(
      kCGWindowListOptionOnScreenOnly | kCGWindowListExcludeDesktopElements, kCGNullWindowID);
  if (!windows) return -1;
  pid_t pid = -1;
  CFIndex count = CFArrayGetCount(windows);
  for (CFIndex i = 0; i < count && pid < 0; i += 1) {
    CFDictionaryRef window =
        static_cast<CFDictionaryRef>(CFArrayGetValueAtIndex(windows, i));
    if (!window) continue;
    CFNumberRef layerRef =
        static_cast<CFNumberRef>(CFDictionaryGetValue(window, kCGWindowLayer));
    int layer = -1;
    if (!layerRef || !CFNumberGetValue(layerRef, kCFNumberIntType, &layer) || layer != 0) {
      continue;
    }
    CFNumberRef ownerRef =
        static_cast<CFNumberRef>(CFDictionaryGetValue(window, kCGWindowOwnerPID));
    int owner = -1;
    if (ownerRef && CFNumberGetValue(ownerRef, kCFNumberIntType, &owner)) {
      pid = static_cast<pid_t>(owner);
    }
  }
  CFRelease(windows);
  return pid;
}

/** Copies the focused element of `pid`, with the timeout already applied. Caller CFReleases. */
AXUIElementRef CopyFocusedElement(pid_t pid, double timeoutMs) {
  AXUIElementRef app = AXUIElementCreateApplication(pid);
  if (!app) return NULL;
  ApplyTimeout(app, timeoutMs);
  CFTypeRef focused = NULL;
  AXError error = AXUIElementCopyAttributeValue(app, kAXFocusedUIElementAttribute, &focused);
  CFRelease(app);
  if (error != kAXErrorSuccess || !focused) return NULL;
  if (CFGetTypeID(focused) != AXUIElementGetTypeID()) {
    CFRelease(focused);
    return NULL;
  }
  AXUIElementRef element = static_cast<AXUIElementRef>(focused);
  ApplyTimeout(element, timeoutMs);
  return element;
}

// ── Async workers ───────────────────────────────────────────────────────────

/** Shared promise plumbing: every worker here resolves a JS promise or rejects with an Error. */
class PromiseWorker : public Napi::AsyncWorker {
 public:
  explicit PromiseWorker(Napi::Env env)
      : Napi::AsyncWorker(env), deferred_(Napi::Promise::Deferred::New(env)) {}

  Napi::Promise Promise() { return deferred_.Promise(); }

 protected:
  void OnError(const Napi::Error& error) override { deferred_.Reject(error.Value()); }

  Napi::Promise::Deferred deferred_;
};

class ReadFocusedWorker : public PromiseWorker {
 public:
  ReadFocusedWorker(Napi::Env env, pid_t pid, double timeoutMs, CFIndex valueMaxChars)
      : PromiseWorker(env), pid_(pid), timeoutMs_(timeoutMs), valueMaxChars_(valueMaxChars) {}

  void Execute() override {
    AXUIElementRef element = CopyFocusedElement(pid_, timeoutMs_);
    if (!element) return;

    ReadIdentity(element, &identity_);
    // A password field's text must not reach the JS heap at all. macOS normally withholds it from
    // AXValue, but the classification is cheap here and this is the earliest point it can hold —
    // TypeScript rejecting the element later is a second line, not the first.
    if (identity_.subrole != "AXSecureTextField") {
      ReadTextState(element, valueMaxChars_, &state_);
    }
    attributeNames_ = CopyAttributeNames(element);
    valueSettable_ = IsAttributeSettable(element, kAXValueAttribute);
    selectedTextSettable_ = IsAttributeSettable(element, kAXSelectedTextAttribute);
    enabled_ = CopyAxBool(element, kAXEnabledAttribute, true);
    CGPoint origin = CGPointZero;
    CGSize size = CGSizeZero;
    if (CopyAxPoint(element, kAXPositionAttribute, &origin) &&
        CopyAxSize(element, kAXSizeAttribute, &size)) {
      hasFrame_ = true;
      frame_ = CGRectMake(origin.x, origin.y, size.width, size.height);
      frameOnScreen_ = FrameIntersectsAnyDisplay(frame_);
    }
    token_ = ElementRegistry::Shared().Store(element);
    found_ = true;
    CFRelease(element);
  }

  void OnOK() override {
    Napi::Env env = Env();
    if (!found_) {
      deferred_.Resolve(env.Null());
      return;
    }
    Napi::Object result = TextStateToObject(env, state_);
    AssignIdentity(result, identity_);
    result.Set("token", Napi::String::New(env, token_));
    result.Set("valueSettable", Napi::Boolean::New(env, valueSettable_));
    result.Set("selectedTextSettable", Napi::Boolean::New(env, selectedTextSettable_));
    result.Set("enabled", Napi::Boolean::New(env, enabled_));
    if (hasFrame_) {
      Napi::Object frame = Napi::Object::New(env);
      frame.Set("x", Napi::Number::New(env, frame_.origin.x));
      frame.Set("y", Napi::Number::New(env, frame_.origin.y));
      frame.Set("width", Napi::Number::New(env, frame_.size.width));
      frame.Set("height", Napi::Number::New(env, frame_.size.height));
      result.Set("frame", frame);
      result.Set("frameOnScreen", Napi::Boolean::New(env, frameOnScreen_));
    } else {
      result.Set("frame", env.Null());
      result.Set("frameOnScreen", Napi::Boolean::New(env, true));
    }
    Napi::Array attributes = Napi::Array::New(env, attributeNames_.size());
    for (size_t i = 0; i < attributeNames_.size(); i += 1) {
      attributes.Set(i, Napi::String::New(env, attributeNames_[i]));
    }
    result.Set("attributeNames", attributes);
    deferred_.Resolve(result);
  }

 private:
  pid_t pid_;
  double timeoutMs_;
  CFIndex valueMaxChars_;
  bool found_ = false;
  std::string token_;
  ElementIdentity identity_;
  TextState state_;
  std::vector<std::string> attributeNames_;
  bool valueSettable_ = false;
  bool selectedTextSettable_ = false;
  bool enabled_ = true;
  bool hasFrame_ = false;
  CGRect frame_ = CGRectZero;
  bool frameOnScreen_ = true;
};

/**
 * Re-reads the identity of the app's currently focused element and reports whether it is the very
 * same element object captured earlier (CFEqual on the AXUIElementRef, which is stronger than any
 * attribute comparison). TypeScript still compares the identity string on top of this.
 */
class VerifyWorker : public PromiseWorker {
 public:
  VerifyWorker(Napi::Env env, std::string token, pid_t pid, double timeoutMs)
      : PromiseWorker(env), token_(std::move(token)), pid_(pid), timeoutMs_(timeoutMs) {}

  void Execute() override {
    AXUIElementRef captured = ElementRegistry::Shared().Copy(token_);
    if (!captured) return;
    AXUIElementRef focused = CopyFocusedElement(pid_, timeoutMs_);
    if (!focused) {
      CFRelease(captured);
      return;
    }
    sameElement_ = CFEqual(captured, focused) ? true : false;
    ReadIdentity(focused, &identity_);
    enabled_ = CopyAxBool(focused, kAXEnabledAttribute, true);
    found_ = true;
    CFRelease(focused);
    CFRelease(captured);
  }

  void OnOK() override {
    Napi::Env env = Env();
    if (!found_) {
      deferred_.Resolve(env.Null());
      return;
    }
    Napi::Object result = Napi::Object::New(env);
    AssignIdentity(result, identity_);
    result.Set("sameElement", Napi::Boolean::New(env, sameElement_));
    result.Set("enabled", Napi::Boolean::New(env, enabled_));
    deferred_.Resolve(result);
  }

 private:
  std::string token_;
  pid_t pid_;
  double timeoutMs_;
  bool found_ = false;
  bool sameElement_ = false;
  bool enabled_ = true;
  ElementIdentity identity_;
};

/**
 * Sets one text attribute and reads the element back in the same trip. The read-back is the only
 * way to tell a real write from the silent no-op many apps return success for.
 */
class SetTextWorker : public PromiseWorker {
 public:
  SetTextWorker(Napi::Env env, std::string token, CFStringRef attribute, std::string text,
                double timeoutMs, CFIndex valueMaxChars)
      : PromiseWorker(env),
        token_(std::move(token)),
        attribute_(attribute),
        text_(std::move(text)),
        timeoutMs_(timeoutMs),
        valueMaxChars_(valueMaxChars) {}

  void Execute() override {
    AXUIElementRef element = ElementRegistry::Shared().Copy(token_);
    if (!element) {
      error_ = "unknown-token";
      return;
    }
    ApplyTimeout(element, timeoutMs_);
    CFStringRef value = CreateCFString(text_);
    if (!value) {
      CFRelease(element);
      error_ = "encoding-failed";
      return;
    }
    AXError result = AXUIElementSetAttributeValue(element, attribute_, value);
    CFRelease(value);
    ok_ = result == kAXErrorSuccess;
    if (!ok_) error_ = "ax-error-" + std::to_string(static_cast<int>(result));
    ReadTextState(element, valueMaxChars_, &after_);
    hasAfter_ = true;
    CFRelease(element);
  }

  void OnOK() override {
    Napi::Env env = Env();
    Napi::Object result = Napi::Object::New(env);
    result.Set("ok", Napi::Boolean::New(env, ok_));
    result.Set("error", error_.empty() ? env.Null() : Napi::String::New(env, error_).As<Napi::Value>());
    result.Set("after", hasAfter_ ? TextStateToObject(env, after_).As<Napi::Value>() : env.Null());
    deferred_.Resolve(result);
  }

 private:
  std::string token_;
  CFStringRef attribute_;
  std::string text_;
  double timeoutMs_;
  CFIndex valueMaxChars_;
  bool ok_ = false;
  bool hasAfter_ = false;
  std::string error_;
  TextState after_;
};

/**
 * Reads only [range] of the element's text via the parameterized AXStringForRange attribute,
 * falling back to slicing a full value read for views that do not implement it. Either way the
 * caller pays O(range) marshalling, not O(document). Caller CFReleases *out on true.
 */
bool CopyStringForRange(AXUIElementRef element, CFRange range, CFStringRef* out) {
  AXValueRef rangeValue = AXValueCreate(kAXValueTypeCFRange, &range);
  if (rangeValue) {
    CFTypeRef result = NULL;
    AXError err = AXUIElementCopyParameterizedAttributeValue(
        element, kAXStringForRangeParameterizedAttribute, rangeValue, &result);
    CFRelease(rangeValue);
    if (err == kAXErrorSuccess && result) {
      if (CFGetTypeID(result) == CFStringGetTypeID()) {
        *out = static_cast<CFStringRef>(result);
        return true;
      }
      CFRelease(result);
    }
  }
  CFTypeRef value = NULL;
  if (AXUIElementCopyAttributeValue(element, kAXValueAttribute, &value) != kAXErrorSuccess ||
      !value) {
    return false;
  }
  if (CFGetTypeID(value) != CFStringGetTypeID()) {
    CFRelease(value);
    return false;
  }
  CFStringRef whole = static_cast<CFStringRef>(value);
  CFIndex length = CFStringGetLength(whole);
  if (range.location > length || range.location + range.length > length) {
    CFRelease(whole);
    return false;
  }
  CFStringRef slice = CFStringCreateWithSubstring(kCFAllocatorDefault, whole, range);
  CFRelease(whole);
  if (!slice) return false;
  *out = slice;
  return true;
}

/** Whether the element's text over [location, location+expected.size()) equals `expected`. */
bool RegionEquals(AXUIElementRef element, CFIndex location, const std::u16string& expected) {
  if (expected.empty()) return true;
  CFStringRef actual = NULL;
  if (!CopyStringForRange(element,
                          CFRangeMake(location, static_cast<CFIndex>(expected.size())),
                          &actual)) {
    return false;
  }
  CFStringRef wanted = CFStringCreateWithCharacters(
      kCFAllocatorDefault, reinterpret_cast<const UniChar*>(expected.data()),
      static_cast<CFIndex>(expected.size()));
  bool equal = wanted && CFStringCompare(actual, wanted, 0) == kCFCompareEqualTo;
  CFRelease(actual);
  if (wanted) CFRelease(wanted);
  return equal;
}

/**
 * Compare-and-swap on a text region: the streaming hot path, fused into ONE worker trip.
 *
 * Sequence, all against the pinned element without ever crossing back into JavaScript:
 *   1. prove the element is still its application's focused element (CFEqual — by-reference,
 *      stronger than any attribute comparison)
 *   2. compare: the region [regionStart, regionStart+expected.len) must hold exactly `expected`
 *      — a content precondition strictly stronger than an identity re-read, and the reason no
 *      frontmost check appears here: an Accessibility write lands on the element it references,
 *      so unlike the synthetic-event rungs there is no misdirection for a frontmost check to
 *      prevent
 *   3. swap: select the TS-computed edit span inside the region and replace the selection
 *   4. verify the resulting region text, with one blocking settle retry for views that mirror
 *      their text asynchronously
 *   5. park the caret at the TS-chosen position — skipped when the live caret was not where the
 *      last update left it, because then the user moved it and it is not ours to move back
 *
 * Every offset is UTF-16 units on both sides (JavaScript strings and CFRange agree), so values
 * pass through untranslated. The fallback ladder and every retry POLICY stay in TypeScript;
 * this is one atomic primitive, not a strategy.
 */
class CasRangeEditWorker : public PromiseWorker {
 public:
  CasRangeEditWorker(Napi::Env env, std::string token, CFIndex regionStart,
                     std::u16string expected, CFIndex editStart, CFIndex editEnd,
                     std::u16string replacement, CFIndex parkAt, CFIndex expectedCaret,
                     bool preferSplice, double timeoutMs)
      : PromiseWorker(env),
        token_(std::move(token)),
        regionStart_(regionStart),
        expected_(std::move(expected)),
        editStart_(editStart),
        editEnd_(editEnd),
        replacement_(std::move(replacement)),
        parkAt_(parkAt),
        expectedCaret_(expectedCaret),
        preferSplice_(preferSplice),
        timeoutMs_(timeoutMs) {}

  void Execute() override {
    AXUIElementRef element = ElementRegistry::Shared().Copy(token_);
    if (!element) {
      reason_ = "element-gone";
      return;
    }
    ApplyTimeout(element, timeoutMs_);

    pid_t pid = -1;
    if (AXUIElementGetPid(element, &pid) != kAXErrorSuccess) {
      CFRelease(element);
      reason_ = "element-gone";
      return;
    }
    AXUIElementRef focused = CopyFocusedElement(pid, timeoutMs_);
    if (!focused) {
      CFRelease(element);
      reason_ = "element-gone";
      return;
    }
    bool sameElement = CFEqual(element, focused) ? true : false;
    CFRelease(focused);
    if (!sameElement) {
      CFRelease(element);
      reason_ = "element-changed";
      return;
    }

    // The user's caret, before we touch anything: if it is not where the last update parked
    // it, the user moved it and the park below must not fight them.
    bool caretIsOurs = expectedCaret_ < 0;
    CFRange liveSelection = CFRangeMake(0, 0);
    if (CopyAxRange(element, kAXSelectedTextRangeAttribute, &liveSelection)) {
      if (expectedCaret_ >= 0) {
        caretIsOurs = liveSelection.length == 0 && liveSelection.location == expectedCaret_;
      }
    }

    if (!RegionEquals(element, regionStart_, expected_)) {
      CFRelease(element);
      reason_ = "region-mismatch";
      return;
    }

    CFRange editRange =
        CFRangeMake(regionStart_ + editStart_, editEnd_ - editStart_);
    AXValueRef editValue = AXValueCreate(kAXValueTypeCFRange, &editRange);
    if (!editValue) {
      CFRelease(element);
      reason_ = "select-failed";
      return;
    }
    AXError selectError =
        AXUIElementSetAttributeValue(element, kAXSelectedTextRangeAttribute, editValue);
    CFRelease(editValue);
    if (selectError != kAXErrorSuccess) {
      CFRelease(element);
      reason_ = "select-failed";
      return;
    }
    // Placement must be read back on the mirror-settle schedule: Chromium reports the OLD
    // selection in the same trip and lands the new one moments later.
    bool placedOk = false;
    for (int attempt = 0; attempt <= kMirrorSettleSteps && !placedOk; attempt += 1) {
      if (attempt > 0) usleep(kMirrorSettleUs[attempt - 1]);
      CFRange placed = CFRangeMake(-1, -1);
      placedOk = CopyAxRange(element, kAXSelectedTextRangeAttribute, &placed) &&
                 placed.location == editRange.location && placed.length == editRange.length;
    }
    if (!placedOk) {
      CFRelease(element);
      reason_ = "select-failed";
      return;
    }

    // The final region = expected with the edit span replaced, spliced here mechanically from
    // the TS-provided pieces.
    std::u16string finalRegion = expected_.substr(0, static_cast<size_t>(editStart_));
    finalRegion += replacement_;
    finalRegion += expected_.substr(static_cast<size_t>(editEnd_));

    bool landed = false;
    if (!preferSplice_) {
      CFStringRef replacementValue = CFStringCreateWithCharacters(
          kCFAllocatorDefault, reinterpret_cast<const UniChar*>(replacement_.data()),
          static_cast<CFIndex>(replacement_.size()));
      if (!replacementValue) {
        CFRelease(element);
        reason_ = "write-failed";
        return;
      }
      AXError writeError =
          AXUIElementSetAttributeValue(element, kAXSelectedTextAttribute, replacementValue);
      CFRelease(replacementValue);
      // Quick check only — immediate plus one short settle. Exhausting the full schedule here
      // would bill every update in an engine that ignores this attribute for the discovery.
      if (writeError == kAXErrorSuccess) {
        for (int attempt = 0; attempt < 2 && !landed; attempt += 1) {
          if (attempt > 0) usleep(kMirrorSettleUs[0]);
          landed = RegionEquals(element, regionStart_, finalRegion);
        }
      }
      if (landed) via_ = "selected-text";
    }

    if (!landed) {
      // Second swap tactic, same contract: Chromium accepts selection-range and whole-value
      // writes but silently ignores kAXSelectedTextAttribute (measured — reported success,
      // text unchanged). Splice the region into the full value and write THAT. Costs
      // O(document) payload where the first tactic is O(edit), which is why it is the
      // fallback — and why the caller can pass preferSplice once it learns which tactic the
      // target answers to.
      landed = SpliceValueAndVerify(element, finalRegion);
      if (landed) via_ = "value-splice";
    }
    if (!landed) {
      CFRelease(element);
      reason_ = "verify-failed";
      return;
    }

    if (parkAt_ >= 0 && caretIsOurs) {
      CFRange park = CFRangeMake(parkAt_, 0);
      AXValueRef parkValue = AXValueCreate(kAXValueTypeCFRange, &park);
      if (parkValue) {
        AXUIElementSetAttributeValue(element, kAXSelectedTextRangeAttribute, parkValue);
        CFRelease(parkValue);
        parked_ = true;
      }
    }
    ok_ = true;
    CFRelease(element);
  }

  void OnOK() override {
    Napi::Env env = Env();
    Napi::Object result = Napi::Object::New(env);
    result.Set("ok", Napi::Boolean::New(env, ok_));
    result.Set("reason",
               reason_.empty() ? env.Null() : Napi::String::New(env, reason_).As<Napi::Value>());
    result.Set("parked", Napi::Boolean::New(env, parked_));
    result.Set("via",
               via_.empty() ? env.Null() : Napi::String::New(env, via_).As<Napi::Value>());
    deferred_.Resolve(result);
  }

 private:
  /**
   * Rewrites the whole value with the draft region replaced by `finalRegion`, verifying on the
   * settle schedule. The full value is re-read HERE, in the same worker as the precondition,
   * so text outside the region is the freshest readable state.
   */
  bool SpliceValueAndVerify(AXUIElementRef element, const std::u16string& finalRegion) {
    CFTypeRef current = NULL;
    if (AXUIElementCopyAttributeValue(element, kAXValueAttribute, &current) != kAXErrorSuccess ||
        !current) {
      return false;
    }
    if (CFGetTypeID(current) != CFStringGetTypeID()) {
      CFRelease(current);
      return false;
    }
    CFStringRef value = static_cast<CFStringRef>(current);

    // Rich composers render their placeholder as literal text in the accessibility value while
    // the field is empty. Preserving that as "surrounding text" would MATERIALIZE the
    // placeholder into the document — the app's own input path clears it, a raw value write
    // does not. When the whole value equals the element's declared placeholder, the real
    // content is empty and the splice starts from empty.
    CFTypeRef placeholderRef = NULL;
    bool valueIsPlaceholder = false;
    if (CFStringGetLength(value) > 0 &&
        AXUIElementCopyAttributeValue(element, CFSTR("AXPlaceholderValue"), &placeholderRef) ==
            kAXErrorSuccess &&
        placeholderRef) {
      if (CFGetTypeID(placeholderRef) == CFStringGetTypeID()) {
        valueIsPlaceholder =
            CFStringCompare(value, static_cast<CFStringRef>(placeholderRef), 0) ==
            kCFCompareEqualTo;
      }
      CFRelease(placeholderRef);
    }
    if (valueIsPlaceholder) {
      CFRelease(value);
      // Phantom-relative offsets would splice into text that is not really there; the draft's
      // coordinates are only meaningful against empty content when it starts at zero.
      if (regionStart_ != 0 || !expected_.empty()) return false;
      CFStringRef next = CFStringCreateWithCharacters(
          kCFAllocatorDefault, reinterpret_cast<const UniChar*>(finalRegion.data()),
          static_cast<CFIndex>(finalRegion.size()));
      if (!next) return false;
      AXError wrote = AXUIElementSetAttributeValue(element, kAXValueAttribute, next);
      CFRelease(next);
      if (wrote != kAXErrorSuccess) return false;
      for (int attempt = 0; attempt <= kMirrorSettleSteps; attempt += 1) {
        if (attempt > 0) usleep(kMirrorSettleUs[attempt - 1]);
        if (RegionEquals(element, 0, finalRegion)) return true;
      }
      return false;
    }

    CFIndex length = CFStringGetLength(value);
    CFIndex regionEnd = regionStart_ + static_cast<CFIndex>(expected_.size());
    if (regionStart_ > length || regionEnd > length) {
      CFRelease(value);
      return false;
    }

    std::u16string whole(static_cast<size_t>(length), u'\0');
    CFStringGetCharacters(value, CFRangeMake(0, length),
                          reinterpret_cast<UniChar*>(whole.data()));
    CFRelease(value);
    // The region must still hold what the precondition saw — the splice is positional, and a
    // mid-flight edit would make these offsets someone else's text.
    if (whole.compare(static_cast<size_t>(regionStart_), expected_.size(), expected_) != 0) {
      return false;
    }
    whole.replace(static_cast<size_t>(regionStart_), expected_.size(), finalRegion);

    CFStringRef next = CFStringCreateWithCharacters(
        kCFAllocatorDefault, reinterpret_cast<const UniChar*>(whole.data()),
        static_cast<CFIndex>(whole.size()));
    if (!next) return false;
    AXError wrote = AXUIElementSetAttributeValue(element, kAXValueAttribute, next);
    CFRelease(next);
    if (wrote != kAXErrorSuccess) return false;

    for (int attempt = 0; attempt <= kMirrorSettleSteps; attempt += 1) {
      if (attempt > 0) usleep(kMirrorSettleUs[attempt - 1]);
      if (RegionEquals(element, regionStart_, finalRegion)) return true;
    }
    return false;
  }

  std::string token_;
  CFIndex regionStart_;
  std::u16string expected_;
  CFIndex editStart_;
  CFIndex editEnd_;
  std::u16string replacement_;
  CFIndex parkAt_;
  CFIndex expectedCaret_;
  bool preferSplice_;
  double timeoutMs_;
  bool ok_ = false;
  bool parked_ = false;
  std::string reason_;
  std::string via_;
};

/**
 * Sets the element's selection range — the aiming half of a precise range edit: select
 * [start, start+length), then replace the selection. Reports the range read back in the same
 * trip so TypeScript can tell a landed placement from the silent no-op refusal some views
 * answer with.
 */
class SetSelectionRangeWorker : public PromiseWorker {
 public:
  SetSelectionRangeWorker(Napi::Env env, std::string token, long start, long length,
                          double timeoutMs)
      : PromiseWorker(env),
        token_(std::move(token)),
        start_(start),
        length_(length),
        timeoutMs_(timeoutMs) {}

  void Execute() override {
    AXUIElementRef element = ElementRegistry::Shared().Copy(token_);
    if (!element) {
      error_ = "unknown-token";
      return;
    }
    ApplyTimeout(element, timeoutMs_);
    CFRange range = CFRangeMake(start_, length_);
    AXValueRef value = AXValueCreate(kAXValueTypeCFRange, &range);
    if (!value) {
      CFRelease(element);
      error_ = "encoding-failed";
      return;
    }
    AXError result =
        AXUIElementSetAttributeValue(element, kAXSelectedTextRangeAttribute, value);
    CFRelease(value);
    ok_ = result == kAXErrorSuccess;
    if (!ok_) error_ = "ax-error-" + std::to_string(static_cast<int>(result));
    // Read back on the mirror-settle schedule: Chromium reports the OLD selection in the same
    // trip; without the settle every placement looks failed there.
    CFRange after = CFRangeMake(0, 0);
    for (int attempt = 0; attempt <= kMirrorSettleSteps; attempt += 1) {
      if (attempt > 0) usleep(kMirrorSettleUs[attempt - 1]);
      hasAfter_ = CopyAxRange(element, kAXSelectedTextRangeAttribute, &after);
      if (hasAfter_ && after.location == static_cast<CFIndex>(start_) &&
          after.length == static_cast<CFIndex>(length_)) {
        break;
      }
      if (!ok_) break;
    }
    afterStart_ = static_cast<long>(after.location);
    afterLength_ = static_cast<long>(after.length);
    CFRelease(element);
  }

  void OnOK() override {
    Napi::Env env = Env();
    Napi::Object result = Napi::Object::New(env);
    result.Set("ok", Napi::Boolean::New(env, ok_));
    result.Set("error",
               error_.empty() ? env.Null() : Napi::String::New(env, error_).As<Napi::Value>());
    if (hasAfter_) {
      result.Set("selectionStart", Napi::Number::New(env, static_cast<double>(afterStart_)));
      result.Set("selectionLength", Napi::Number::New(env, static_cast<double>(afterLength_)));
    } else {
      result.Set("selectionStart", env.Null());
      result.Set("selectionLength", env.Null());
    }
    deferred_.Resolve(result);
  }

 private:
  std::string token_;
  long start_;
  long length_;
  double timeoutMs_;
  bool ok_ = false;
  bool hasAfter_ = false;
  long afterStart_ = 0;
  long afterLength_ = 0;
  std::string error_;
};

/**
 * Asks an application to build the accessibility tree it otherwise builds only once it detects
 * assistive technology.
 *
 * Chromium — and so every Electron application — reports no focused element at all until then.
 * `AXManualAccessibility` is the opt-in Chromium added for exactly this. `AXEnhancedUserInterface`
 * would also work and is deliberately not used: it additionally moves and resizes windows out
 * from under third-party window managers.
 *
 * Diagnostic use only. Measured across real Electron applications, the attribute is accepted but
 * does not surface fields that were hidden — treat a positive result as an invitation to
 * re-measure, not as coverage.
 */
class PrimeAccessibilityWorker : public PromiseWorker {
 public:
  PrimeAccessibilityWorker(Napi::Env env, pid_t pid, double timeoutMs)
      : PromiseWorker(env), pid_(pid), timeoutMs_(timeoutMs) {}

  void Execute() override {
    AXUIElementRef app = AXUIElementCreateApplication(pid_);
    if (!app) return;
    ApplyTimeout(app, timeoutMs_);
    ok_ = AXUIElementSetAttributeValue(app, CFSTR("AXManualAccessibility"), kCFBooleanTrue) ==
          kAXErrorSuccess;
    CFRelease(app);
  }

  void OnOK() override { deferred_.Resolve(Napi::Boolean::New(Env(), ok_)); }

 private:
  pid_t pid_;
  double timeoutMs_;
  bool ok_ = false;
};

/** Reads an element's current text state without writing — used to verify a paste landed. */
class ReadStateWorker : public PromiseWorker {
 public:
  ReadStateWorker(Napi::Env env, std::string token, double timeoutMs, CFIndex valueMaxChars)
      : PromiseWorker(env),
        token_(std::move(token)),
        timeoutMs_(timeoutMs),
        valueMaxChars_(valueMaxChars) {}

  void Execute() override {
    AXUIElementRef element = ElementRegistry::Shared().Copy(token_);
    if (!element) return;
    ApplyTimeout(element, timeoutMs_);
    ReadTextState(element, valueMaxChars_, &state_);
    found_ = true;
    CFRelease(element);
  }

  void OnOK() override {
    Napi::Env env = Env();
    deferred_.Resolve(found_ ? TextStateToObject(env, state_).As<Napi::Value>() : env.Null());
  }

 private:
  std::string token_;
  double timeoutMs_;
  CFIndex valueMaxChars_;
  bool found_ = false;
  TextState state_;
};

/**
 * The on-screen rectangle of a text range — a zero-length range at the caret returns the caret's
 * own rectangle. Lets a caller anchor UI (a HUD, ghost text, a correction popover) to the exact
 * insertion point. `AXBoundsForRange` answers in global screen coordinates on AppKit and web
 * content alike; when the element exposes no range at the caret, the last glyph's trailing edge
 * keeps real line height where an empty-caret rectangle would collapse to nothing.
 */
class CaretBoundsWorker : public PromiseWorker {
 public:
  CaretBoundsWorker(Napi::Env env, std::string token, double timeoutMs)
      : PromiseWorker(env), token_(std::move(token)), timeoutMs_(timeoutMs) {}

  void Execute() override {
    AXUIElementRef element = ElementRegistry::Shared().Copy(token_);
    if (!element) return;
    ApplyTimeout(element, timeoutMs_);

    CFRange selection = CFRangeMake(0, 0);
    bool haveSelection = CopyAxRange(element, kAXSelectedTextRangeAttribute, &selection);
    long caret = haveSelection ? selection.location : 0;

    if (BoundsForRange(element, CFRangeMake(caret, 0), &rect_)) {
      found_ = true;
    } else if (caret > 0 && BoundsForRange(element, CFRangeMake(caret - 1, 1), &rect_)) {
      // A collapsed caret range was refused; the previous glyph's box carries the line height.
      rect_.origin.x += rect_.size.width;
      rect_.size.width = 0;
      found_ = true;
    }
    CFRelease(element);
  }

  void OnOK() override {
    Napi::Env env = Env();
    if (!found_) {
      deferred_.Resolve(env.Null());
      return;
    }
    Napi::Object result = Napi::Object::New(env);
    result.Set("x", Napi::Number::New(env, rect_.origin.x));
    result.Set("y", Napi::Number::New(env, rect_.origin.y));
    result.Set("width", Napi::Number::New(env, rect_.size.width));
    result.Set("height", Napi::Number::New(env, rect_.size.height));
    deferred_.Resolve(result);
  }

 private:
  static bool BoundsForRange(AXUIElementRef element, CFRange range, CGRect* out) {
    AXValueRef rangeValue = AXValueCreate(kAXValueTypeCFRange, &range);
    if (!rangeValue) return false;
    CFTypeRef result = NULL;
    AXError error = AXUIElementCopyParameterizedAttributeValue(
        element, kAXBoundsForRangeParameterizedAttribute, rangeValue, &result);
    CFRelease(rangeValue);
    if (error != kAXErrorSuccess || !result) return false;
    bool ok = CFGetTypeID(result) == AXValueGetTypeID() &&
              AXValueGetType(static_cast<AXValueRef>(result)) == kAXValueTypeCGRect &&
              AXValueGetValue(static_cast<AXValueRef>(result), kAXValueTypeCGRect, out);
    CFRelease(result);
    return ok;
  }

  std::string token_;
  double timeoutMs_;
  bool found_ = false;
  CGRect rect_ = CGRectZero;
};

/**
 * Replaces a text range in one native call via the AXReplaceRangeWithText parameterized
 * attribute. On AppKit this routes through the focused element's input context — the same
 * insertText:replacementRange: path IMEs and Dictation use, so it coalesces into native undo and
 * fires the delegate/formatter notifications a raw value write skips; on WebKit it is a
 * first-class editing command. Chromium does not implement it (advertised but inert), so the
 * caller keeps this above the two-step selection write only as a preference and falls through on
 * failure.
 *
 * The parameter dictionary keys are exact and load-bearing: a wrong key decodes to an empty
 * range and DELETES the target while still reporting success. The result is a CFBoolean, so the
 * caller verifies by read-back regardless.
 */
class ReplaceRangeWorker : public PromiseWorker {
 public:
  ReplaceRangeWorker(Napi::Env env, std::string token, CFIndex start, CFIndex length,
                     std::u16string text, double timeoutMs)
      : PromiseWorker(env),
        token_(std::move(token)),
        start_(start),
        length_(length),
        text_(std::move(text)),
        timeoutMs_(timeoutMs) {}

  void Execute() override {
    AXUIElementRef element = ElementRegistry::Shared().Copy(token_);
    if (!element) {
      error_ = "element-gone";
      return;
    }
    ApplyTimeout(element, timeoutMs_);

    CFRange range = CFRangeMake(start_, length_);
    AXValueRef rangeValue = AXValueCreate(kAXValueTypeCFRange, &range);
    CFStringRef replacement = CFStringCreateWithCharacters(
        kCFAllocatorDefault, reinterpret_cast<const UniChar*>(text_.data()),
        static_cast<CFIndex>(text_.size()));
    if (!rangeValue || !replacement) {
      if (rangeValue) CFRelease(rangeValue);
      if (replacement) CFRelease(replacement);
      CFRelease(element);
      error_ = "encoding-failed";
      return;
    }

    CFTypeRef keys[] = {CFSTR("AXReplacementRange"), CFSTR("AXReplacementText")};
    CFTypeRef values[] = {rangeValue, replacement};
    CFDictionaryRef params =
        CFDictionaryCreate(kCFAllocatorDefault, keys, values, 2,
                           &kCFTypeDictionaryKeyCallBacks, &kCFTypeDictionaryValueCallBacks);
    CFTypeRef result = NULL;
    AXError error = AXUIElementCopyParameterizedAttributeValue(
        element, CFSTR("AXReplaceRangeWithText"), params, &result);
    CFRelease(params);
    CFRelease(rangeValue);
    CFRelease(replacement);

    if (error == kAXErrorSuccess && result) {
      ok_ = CFGetTypeID(result) == CFBooleanGetTypeID() &&
            CFBooleanGetValue(static_cast<CFBooleanRef>(result));
    }
    if (result) CFRelease(result);
    if (!ok_) error_ = "unsupported";
    CFRelease(element);
  }

  void OnOK() override {
    Napi::Env env = Env();
    Napi::Object result = Napi::Object::New(env);
    result.Set("ok", Napi::Boolean::New(env, ok_));
    result.Set("error",
               error_.empty() ? env.Null() : Napi::String::New(env, error_).As<Napi::Value>());
    deferred_.Resolve(result);
  }

 private:
  std::string token_;
  CFIndex start_;
  CFIndex length_;
  std::u16string text_;
  double timeoutMs_;
  bool ok_ = false;
  std::string error_;
};

/**
 * Performs the element's AXConfirm action — the accessibility "commit this field" verb some
 * single-line controls expose, a keystroke-free alternative to posting Return. Resolves whether
 * the element advertised the action and it succeeded; the caller keeps the Return chord as the
 * fallback for the many fields (multiline text areas among them) that expose no such action.
 */
class ConfirmWorker : public PromiseWorker {
 public:
  ConfirmWorker(Napi::Env env, std::string token, double timeoutMs)
      : PromiseWorker(env), token_(std::move(token)), timeoutMs_(timeoutMs) {}

  void Execute() override {
    AXUIElementRef element = ElementRegistry::Shared().Copy(token_);
    if (!element) return;
    ApplyTimeout(element, timeoutMs_);

    CFArrayRef actions = NULL;
    if (AXUIElementCopyActionNames(element, &actions) == kAXErrorSuccess && actions) {
      CFIndex count = CFArrayGetCount(actions);
      for (CFIndex i = 0; i < count && !advertised_; i += 1) {
        CFTypeRef entry = CFArrayGetValueAtIndex(actions, i);
        if (entry && CFGetTypeID(entry) == CFStringGetTypeID() &&
            CFStringCompare(static_cast<CFStringRef>(entry), kAXConfirmAction, 0) ==
                kCFCompareEqualTo) {
          advertised_ = true;
        }
      }
      CFRelease(actions);
    }
    if (advertised_) {
      ok_ = AXUIElementPerformAction(element, kAXConfirmAction) == kAXErrorSuccess;
    }
    CFRelease(element);
  }

  void OnOK() override {
    Napi::Env env = Env();
    Napi::Object result = Napi::Object::New(env);
    result.Set("ok", Napi::Boolean::New(env, ok_));
    result.Set("advertised", Napi::Boolean::New(env, advertised_));
    deferred_.Resolve(result);
  }

 private:
  std::string token_;
  double timeoutMs_;
  bool advertised_ = false;
  bool ok_ = false;
};

/** Types text as synthetic Unicode key events, chunked, with a gap apps' input handling tolerates. */
class TypeUnicodeWorker : public PromiseWorker {
 public:
  TypeUnicodeWorker(Napi::Env env, pid_t expectedPid, std::vector<UniChar> units)
      : PromiseWorker(env), expectedPid_(expectedPid), units_(std::move(units)) {}

  void Execute() override {
    CGEventSourceRef source = CGEventSourceCreate(kCGEventSourceStateHIDSystemState);
    for (size_t offset = 0; offset < units_.size(); offset += kTypeChunkUnits) {
      size_t count = std::min(static_cast<size_t>(kTypeChunkUnits), units_.size() - offset);
      CGEventRef down = CGEventCreateKeyboardEvent(source, 0, true);
      CGEventRef up = CGEventCreateKeyboardEvent(source, 0, false);
      if (!down || !up) {
        if (down) CFRelease(down);
        if (up) CFRelease(up);
        ok_ = false;
        break;
      }
      // Flags left over from a still-settling hotkey chord would turn typed characters into
      // shortcuts; a Unicode payload never wants modifiers.
      CGEventSetFlags(down, static_cast<CGEventFlags>(0));
      CGEventSetFlags(up, static_cast<CGEventFlags>(0));
      CGEventKeyboardSetUnicodeString(down, static_cast<UniCharCount>(count), &units_[offset]);
      CGEventKeyboardSetUnicodeString(up, static_cast<UniCharCount>(count), &units_[offset]);
      CGEventPostToPid(expectedPid_, down);
      CGEventPostToPid(expectedPid_, up);
      CFRelease(down);
      CFRelease(up);
      usleep(kTypeChunkDelayUs);
    }
    if (source) CFRelease(source);
  }

  void OnOK() override {
    bool remainedFrontmost = FocusedAppPid() == expectedPid_;
    deferred_.Resolve(Napi::Boolean::New(Env(), ok_ && remainedFrontmost));
  }

 private:
  pid_t expectedPid_;
  std::vector<UniChar> units_;
  bool ok_ = true;
};

// ── Argument guards ─────────────────────────────────────────────────────────

/**
 * With NAPI_DISABLE_CPP_EXCEPTIONS a bad `.As<>()` does not throw — it sets a pending JS exception
 * and returns a default-constructed value, and calling further N-API functions in that state is
 * documented as unsafe. A wrong call from TypeScript would therefore take the process down instead
 * of raising a TypeError, so every exported function checks its arguments first.
 */
enum class ArgKind { Number, String };

bool ArgsMatch(const Napi::CallbackInfo& info, std::initializer_list<ArgKind> expected) {
  if (info.Length() < expected.size()) return false;
  size_t index = 0;
  for (ArgKind kind : expected) {
    const Napi::Value value = info[index];
    if (kind == ArgKind::Number && !value.IsNumber()) return false;
    if (kind == ArgKind::String && !value.IsString()) return false;
    index += 1;
  }
  return true;
}

/** Async entry points report a bad call as a rejection rather than a crash. */
Napi::Value RejectBadArgs(Napi::Env env, const char* signature) {
  auto deferred = Napi::Promise::Deferred::New(env);
  deferred.Reject(Napi::TypeError::New(env, signature).Value());
  return deferred.Promise();
}

// ── Synchronous entry points (cheap, main-thread APIs) ──────────────────────

Napi::Value IsAccessibilityTrusted(const Napi::CallbackInfo& info) {
  // The options variant, not AXIsProcessTrusted(): the plain call caches its first answer for
  // the process lifetime, so a grant revoked mid-run keeps reading as trusted forever.
  return Napi::Boolean::New(info.Env(), AXIsProcessTrustedWithOptions(NULL) ? true : false);
}

/**
 * Names the process holding the Secure Event Input grab, or null. The pid lives in the
 * IOConsoleUsers property on the IORegistry ROOT entry — not under IOResources, as most
 * write-ups claim. Best effort by Apple's own design: no reliable API is documented, and the
 * pid can be wrong or absent when the grab was taken while the app was backgrounded.
 */
Napi::Value SecureInputCulprit(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!IsSecureEventInputEnabled()) return env.Null();

  // kIOMainPortDefault is macOS 12+; the deployment target is 11. Both spellings are the same
  // NULL-equivalent default port, so passing 0 works on every supported version without an
  // availability guard around the call.
  io_registry_entry_t root = IORegistryGetRootEntry(MACH_PORT_NULL);
  if (!root) return env.Null();
  CFTypeRef users =
      IORegistryEntryCreateCFProperty(root, CFSTR("IOConsoleUsers"), kCFAllocatorDefault, 0);
  IOObjectRelease(root);
  if (!users) return env.Null();

  pid_t culpritPid = -1;
  if (CFGetTypeID(users) == CFArrayGetTypeID()) {
    CFArrayRef array = static_cast<CFArrayRef>(users);
    for (CFIndex i = 0; i < CFArrayGetCount(array) && culpritPid < 0; i += 1) {
      CFTypeRef entry = CFArrayGetValueAtIndex(array, i);
      if (!entry || CFGetTypeID(entry) != CFDictionaryGetTypeID()) continue;
      CFTypeRef pidRef = CFDictionaryGetValue(static_cast<CFDictionaryRef>(entry),
                                              CFSTR("kCGSSessionSecureInputPID"));
      if (pidRef && CFGetTypeID(pidRef) == CFNumberGetTypeID()) {
        int value = -1;
        if (CFNumberGetValue(static_cast<CFNumberRef>(pidRef), kCFNumberIntType, &value)) {
          culpritPid = static_cast<pid_t>(value);
        }
      }
    }
  }
  CFRelease(users);
  if (culpritPid <= 0) return env.Null();

  Napi::Object result = Napi::Object::New(env);
  result.Set("pid", Napi::Number::New(env, static_cast<double>(culpritPid)));
  NSRunningApplication* app =
      [NSRunningApplication runningApplicationWithProcessIdentifier:culpritPid];
  const char* name = app && app.localizedName ? app.localizedName.UTF8String : NULL;
  const char* bundleId = app && app.bundleIdentifier ? app.bundleIdentifier.UTF8String : NULL;
  result.Set("name", Napi::String::New(env, name ? name : ""));
  result.Set("bundleId", Napi::String::New(env, bundleId ? bundleId : ""));
  return result;
}

/** The modifier flags the user is physically holding right now, masked to the four that turn a
 *  keystroke into a shortcut. */
Napi::Value CurrentModifierFlags(const Napi::CallbackInfo& info) {
  CGEventFlags flags = CGEventSourceFlagsState(kCGEventSourceStateCombinedSessionState);
  constexpr CGEventFlags interesting = kCGEventFlagMaskCommand | kCGEventFlagMaskShift |
                                       kCGEventFlagMaskControl | kCGEventFlagMaskAlternate;
  return Napi::Number::New(info.Env(), static_cast<double>(flags & interesting));
}

/**
 * Secure Event Input is on whenever any app has a password field up. It suppresses synthetic
 * events system-wide, so delivery attempted under it can silently go nowhere.
 */
Napi::Value IsSecureInputEnabled(const Napi::CallbackInfo& info) {
  return Napi::Boolean::New(info.Env(), IsSecureEventInputEnabled() ? true : false);
}

Napi::Value FrontmostApp(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  pid_t focusedPid = FocusedAppPid();
  // By-pid lookup is a fresh query, unlike the notification-fed frontmostApplication. The
  // NSWorkspace value remains the fallback when accessibility is not granted.
  NSRunningApplication* app =
      focusedPid > 0 ? [NSRunningApplication runningApplicationWithProcessIdentifier:focusedPid]
                     : [[NSWorkspace sharedWorkspace] frontmostApplication];
  if (!app) return env.Null();
  Napi::Object result = Napi::Object::New(env);
  result.Set("pid", Napi::Number::New(env, static_cast<double>(app.processIdentifier)));
  const char* bundleId = app.bundleIdentifier ? app.bundleIdentifier.UTF8String : NULL;
  const char* name = app.localizedName ? app.localizedName.UTF8String : NULL;
  result.Set("bundleId", Napi::String::New(env, bundleId ? bundleId : ""));
  result.Set("name", Napi::String::New(env, name ? name : ""));
  return result;
}

Napi::Value ReadFocusedElement(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::Number, ArgKind::Number, ArgKind::Number})) {
    return RejectBadArgs(env, "readFocusedElement(pid, timeoutMs, valueMaxChars)");
  }
  pid_t pid = static_cast<pid_t>(info[0].As<Napi::Number>().Int32Value());
  double timeoutMs = info[1].As<Napi::Number>().DoubleValue();
  CFIndex valueMaxChars = static_cast<CFIndex>(info[2].As<Napi::Number>().Int64Value());
  auto* worker = new ReadFocusedWorker(env, pid, timeoutMs, valueMaxChars);
  worker->Queue();
  return worker->Promise();
}

Napi::Value VerifyElement(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::String, ArgKind::Number, ArgKind::Number})) {
    return RejectBadArgs(env, "verifyElement(token, pid, timeoutMs)");
  }
  std::string token = info[0].As<Napi::String>().Utf8Value();
  pid_t pid = static_cast<pid_t>(info[1].As<Napi::Number>().Int32Value());
  double timeoutMs = info[2].As<Napi::Number>().DoubleValue();
  auto* worker = new VerifyWorker(env, std::move(token), pid, timeoutMs);
  worker->Queue();
  return worker->Promise();
}

Napi::Value SetSelectedText(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::String, ArgKind::String, ArgKind::Number, ArgKind::Number})) {
    return RejectBadArgs(env, "setSelectedText(token, text, timeoutMs, valueMaxChars)");
  }
  auto* worker = new SetTextWorker(env, info[0].As<Napi::String>().Utf8Value(),
                                   kAXSelectedTextAttribute, info[1].As<Napi::String>().Utf8Value(),
                                   info[2].As<Napi::Number>().DoubleValue(),
                                   static_cast<CFIndex>(info[3].As<Napi::Number>().Int64Value()));
  worker->Queue();
  return worker->Promise();
}

Napi::Value SetValue(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::String, ArgKind::String, ArgKind::Number, ArgKind::Number})) {
    return RejectBadArgs(env, "setValue(token, text, timeoutMs, valueMaxChars)");
  }
  auto* worker = new SetTextWorker(env, info[0].As<Napi::String>().Utf8Value(), kAXValueAttribute,
                                   info[1].As<Napi::String>().Utf8Value(),
                                   info[2].As<Napi::Number>().DoubleValue(),
                                   static_cast<CFIndex>(info[3].As<Napi::Number>().Int64Value()));
  worker->Queue();
  return worker->Promise();
}

Napi::Value CasRangeEdit(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::String, ArgKind::Number, ArgKind::String, ArgKind::Number,
                        ArgKind::Number, ArgKind::String, ArgKind::Number, ArgKind::Number,
                        ArgKind::Number, ArgKind::Number})) {
    return RejectBadArgs(env,
                         "casRangeEdit(token, regionStart, expected, editStart, editEnd, "
                         "replacement, parkAt, expectedCaret, preferSplice, timeoutMs)");
  }
  auto* worker = new CasRangeEditWorker(
      env, info[0].As<Napi::String>().Utf8Value(),
      static_cast<CFIndex>(info[1].As<Napi::Number>().Int64Value()),
      info[2].As<Napi::String>().Utf16Value(),
      static_cast<CFIndex>(info[3].As<Napi::Number>().Int64Value()),
      static_cast<CFIndex>(info[4].As<Napi::Number>().Int64Value()),
      info[5].As<Napi::String>().Utf16Value(),
      static_cast<CFIndex>(info[6].As<Napi::Number>().Int64Value()),
      static_cast<CFIndex>(info[7].As<Napi::Number>().Int64Value()),
      info[8].As<Napi::Number>().Int64Value() != 0,
      info[9].As<Napi::Number>().DoubleValue());
  worker->Queue();
  return worker->Promise();
}

Napi::Value SetSelectedTextRange(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::String, ArgKind::Number, ArgKind::Number, ArgKind::Number})) {
    return RejectBadArgs(env, "setSelectedTextRange(token, start, length, timeoutMs)");
  }
  auto* worker = new SetSelectionRangeWorker(
      env, info[0].As<Napi::String>().Utf8Value(),
      static_cast<long>(info[1].As<Napi::Number>().Int64Value()),
      static_cast<long>(info[2].As<Napi::Number>().Int64Value()),
      info[3].As<Napi::Number>().DoubleValue());
  worker->Queue();
  return worker->Promise();
}

Napi::Value CaretBounds(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::String, ArgKind::Number})) {
    return RejectBadArgs(env, "caretBounds(token, timeoutMs)");
  }
  auto* worker = new CaretBoundsWorker(env, info[0].As<Napi::String>().Utf8Value(),
                                       info[1].As<Napi::Number>().DoubleValue());
  worker->Queue();
  return worker->Promise();
}

Napi::Value ReplaceRange(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::String, ArgKind::Number, ArgKind::Number, ArgKind::String,
                        ArgKind::Number})) {
    return RejectBadArgs(env, "replaceRange(token, start, length, text, timeoutMs)");
  }
  auto* worker = new ReplaceRangeWorker(
      env, info[0].As<Napi::String>().Utf8Value(),
      static_cast<CFIndex>(info[1].As<Napi::Number>().Int64Value()),
      static_cast<CFIndex>(info[2].As<Napi::Number>().Int64Value()),
      info[3].As<Napi::String>().Utf16Value(), info[4].As<Napi::Number>().DoubleValue());
  worker->Queue();
  return worker->Promise();
}

Napi::Value ConfirmElement(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::String, ArgKind::Number})) {
    return RejectBadArgs(env, "confirmElement(token, timeoutMs)");
  }
  auto* worker = new ConfirmWorker(env, info[0].As<Napi::String>().Utf8Value(),
                                   info[1].As<Napi::Number>().DoubleValue());
  worker->Queue();
  return worker->Promise();
}

Napi::Value PrimeAccessibility(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::Number, ArgKind::Number})) {
    return RejectBadArgs(env, "primeAccessibility(pid, timeoutMs)");
  }
  auto* worker = new PrimeAccessibilityWorker(env,
                                              static_cast<pid_t>(info[0].As<Napi::Number>().Int32Value()),
                                              info[1].As<Napi::Number>().DoubleValue());
  worker->Queue();
  return worker->Promise();
}

Napi::Value ReadElementState(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::String, ArgKind::Number, ArgKind::Number})) {
    return RejectBadArgs(env, "readElementState(token, timeoutMs, valueMaxChars)");
  }
  auto* worker = new ReadStateWorker(env, info[0].As<Napi::String>().Utf8Value(),
                                     info[1].As<Napi::Number>().DoubleValue(),
                                     static_cast<CFIndex>(info[2].As<Napi::Number>().Int64Value()));
  worker->Queue();
  return worker->Promise();
}

/** Creates, flags and posts one keyboard event to `pid`. False when the event could not be made. */
bool PostKeyEvent(CGEventSourceRef source, pid_t pid, CGKeyCode keyCode, bool keyDown,
                  CGEventFlags flags) {
  CGEventRef event = CGEventCreateKeyboardEvent(source, keyCode, keyDown);
  if (!event) return false;
  // Set rather than or-in: any modifier the user still physically holds would otherwise turn this
  // into a different shortcut.
  CGEventSetFlags(event, flags);
  CGEventPostToPid(pid, event);
  CFRelease(event);
  return true;
}

/**
 * Posts one keystroke, optionally wrapped in real modifier key events, while `expectedPid` is
 * frontmost.
 *
 * The frontmost check proves the target still matches the caller's captured intent. The events
 * are then addressed to that process rather than the session stream, so a focus change cannot
 * reroute text into a different application. macOS may drop a process-targeted event after its
 * app loses focus; the final check reports that as a failed delivery, which is safer than
 * misdirection.
 *
 * A modifier is delivered as its own key event and not only as a flag on the keystroke. Toolkits
 * that track modifiers through the events they receive — Chromium, and every Electron application
 * on top of it — never observe Command going down otherwise, and handle the keystroke as a bare
 * "v": the paste silently becomes a typed letter. No wall-clock hold accompanies it, because
 * these events are addressed to the process and consumed from its own queue in order; a hold
 * would only matter for an application polling the system-wide modifier state, which posting to a
 * pid never sets in the first place.
 */
bool PostKeyToFrontmost(pid_t expectedPid, CGKeyCode keyCode, CGKeyCode modifierKeyCode,
                        CGEventFlags flags) {
  if (FocusedAppPid() != expectedPid) return false;

  CGEventSourceRef source = CGEventSourceCreate(kCGEventSourceStateHIDSystemState);
  bool modifierHeld = false;
  if (modifierKeyCode != kNoModifierKey) {
    modifierHeld = PostKeyEvent(source, expectedPid, modifierKeyCode, true, flags);
  }
  bool ok = modifierKeyCode == kNoModifierKey || modifierHeld;
  if (ok) ok = PostKeyEvent(source, expectedPid, keyCode, true, flags);
  if (ok) ok = PostKeyEvent(source, expectedPid, keyCode, false, flags);
  // Released even when the keystroke failed: an application that saw the press and never the
  // release holds Command down against every key the user types next.
  if (modifierHeld) {
    PostKeyEvent(source, expectedPid, modifierKeyCode, false, static_cast<CGEventFlags>(0));
  }
  if (source) CFRelease(source);
  if (!ok) return false;
  // A focus change means the target may have dropped the addressed events.
  return FocusedAppPid() == expectedPid;
}

/**
 * The virtual keycode that produces `wanted` on the CURRENT keyboard layout.
 *
 * Physical keycode 9 is only "V" on QWERTY-shaped layouts. Layouts in the "— QWERTY ⌘" family
 * remap to QWERTY while Command is held, so for them the physical code is right — but on plain
 * Dvorak or Colemak, keycode 9 under Command is ⌘K/⌘…, a different (possibly destructive)
 * command. The two families need opposite answers, so: QWERTY-⌘ variants (input source id
 * carries "QWERTYCMD") keep the physical code, everything else resolves the character through
 * UCKeyTranslate over the layout's own mapping.
 *
 * Resolved fresh per chord rather than cached: a cache would need a layout-change observer, and
 * observers need a serviced run loop this library deliberately does not require. Measured cost —
 * 4µs per steady-state call (128 keycodes, entirely in-process), behind a one-time ~47ms of Text
 * Input Source subsystem initialization on the first call in a process. That first-call cost
 * lands on the first paste of a session; any TSM use would pay it, and a caller who cares can
 * spend it early by resolving once at startup.
 */
CGKeyCode KeyCodeForChar(UniChar wanted, CGKeyCode physicalFallback) {
  TISInputSourceRef layout = TISCopyCurrentKeyboardLayoutInputSource();
  if (!layout) return physicalFallback;

  CFStringRef sourceId = static_cast<CFStringRef>(
      TISGetInputSourceProperty(layout, kTISPropertyInputSourceID));
  if (sourceId &&
      CFStringFind(sourceId, CFSTR("QWERTYCMD"), kCFCompareCaseInsensitive).location !=
          kCFNotFound) {
    CFRelease(layout);
    return physicalFallback;
  }

  CFDataRef layoutData = static_cast<CFDataRef>(
      TISGetInputSourceProperty(layout, kTISPropertyUnicodeKeyLayoutData));
  CGKeyCode resolved = physicalFallback;
  if (layoutData) {
    const UCKeyboardLayout* keyboardLayout =
        reinterpret_cast<const UCKeyboardLayout*>(CFDataGetBytePtr(layoutData));
    for (CGKeyCode code = 0; code < 128; code += 1) {
      UInt32 deadKeyState = 0;
      UniChar chars[4] = {0};
      UniCharCount length = 0;
      OSStatus status = UCKeyTranslate(keyboardLayout, code, kUCKeyActionDisplay, 0,
                                       LMGetKbdType(), kUCKeyTranslateNoDeadKeysBit,
                                       &deadKeyState, 4, &length, chars);
      if (status == noErr && length == 1 &&
          (chars[0] == wanted || chars[0] == wanted + ('A' - 'a'))) {
        resolved = code;
        break;
      }
    }
  }
  CFRelease(layout);
  return resolved;
}

Napi::Value PostPaste(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::Number})) return Napi::Boolean::New(env, false);
  pid_t expectedPid = static_cast<pid_t>(info[0].As<Napi::Number>().Int32Value());
  CGKeyCode vKey = KeyCodeForChar('v', kKeyCodeV);
  return Napi::Boolean::New(
      env, PostKeyToFrontmost(expectedPid, vKey, kKeyCodeCommand, kCGEventFlagMaskCommand));
}

/**
 * Posts Return, optionally with a real modifier, for callers submitting what they inserted.
 * Chat-style applications disagree on the send chord (Enter, Shift-Enter, Cmd-Enter), so the
 * modifier is the caller's choice; unknown modifier strings refuse rather than guess.
 */
Napi::Value PostReturn(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::Number, ArgKind::String})) return Napi::Boolean::New(env, false);
  pid_t expectedPid = static_cast<pid_t>(info[0].As<Napi::Number>().Int32Value());
  std::string modifier = info[1].As<Napi::String>().Utf8Value();
  CGKeyCode modifierKey = kNoModifierKey;
  CGEventFlags flags = static_cast<CGEventFlags>(0);
  if (modifier == "shift") {
    modifierKey = kKeyCodeShift;
    flags = kCGEventFlagMaskShift;
  } else if (modifier == "command") {
    modifierKey = kKeyCodeCommand;
    flags = kCGEventFlagMaskCommand;
  } else if (modifier != "none") {
    return Napi::Boolean::New(env, false);
  }
  return Napi::Boolean::New(env,
                            PostKeyToFrontmost(expectedPid, kKeyCodeReturn, modifierKey, flags));
}

/** Deletes a live selection ahead of typing into editors that replace-on-keydown. */
Napi::Value PostBackspace(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::Number})) return Napi::Boolean::New(env, false);
  pid_t expectedPid = static_cast<pid_t>(info[0].As<Napi::Number>().Int32Value());
  return Napi::Boolean::New(env, PostKeyToFrontmost(expectedPid, kKeyCodeDelete, kNoModifierKey,
                                                    static_cast<CGEventFlags>(0)));
}

Napi::Value TypeUnicode(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::Number, ArgKind::String})) {
    return RejectBadArgs(env, "typeUnicode(expectedPid, text)");
  }
  pid_t expectedPid = static_cast<pid_t>(info[0].As<Napi::Number>().Int32Value());
  if (FocusedAppPid() != expectedPid) {
    auto deferred = Napi::Promise::Deferred::New(env);
    deferred.Resolve(Napi::Boolean::New(env, false));
    return deferred.Promise();
  }

  NSString* text = [NSString stringWithUTF8String:info[1].As<Napi::String>().Utf8Value().c_str()];
  NSUInteger length = text ? text.length : 0;
  if (length == 0 || length > kMaxTypeUnits) {
    auto deferred = Napi::Promise::Deferred::New(env);
    deferred.Resolve(Napi::Boolean::New(env, false));
    return deferred.Promise();
  }

  std::vector<UniChar> units(length);
  [text getCharacters:units.data() range:NSMakeRange(0, length)];
  auto* worker = new TypeUnicodeWorker(env, expectedPid, std::move(units));
  worker->Queue();
  return worker->Promise();
}

// ── Pasteboard ──────────────────────────────────────────────────────────────

Napi::Value PasteboardChangeCount(const Napi::CallbackInfo& info) {
  return Napi::Number::New(info.Env(),
                           static_cast<double>([[NSPasteboard generalPasteboard] changeCount]));
}

/**
 * Copies every flavor of every pasteboard item out of the pasteboard and stashes it natively.
 * The contents never enter the JavaScript heap — the caller gets an opaque token.
 */
Napi::Value PasteboardSnapshot(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  NSPasteboard* pasteboard = [NSPasteboard generalPasteboard];
  NSMutableArray<NSPasteboardItem*>* copies = [NSMutableArray array];
  NSUInteger bytes = 0;
  bool partial = false;

  @try {
    // The per-flavor NSData reads can be large; drain them per item rather than holding every
    // temporary until the next run-loop turn.
    for (NSPasteboardItem* item in pasteboard.pasteboardItems) {
      @autoreleasepool {
        NSPasteboardItem* copy = [[NSPasteboardItem alloc] init];
        bool wroteAny = false;
        for (NSPasteboardType type in item.types) {
          // Checked before the read, not after: NSPasteboardItem cannot report a flavor's size
          // without materializing it, so the budget can only stop the NEXT copy. One oversized
          // flavor is still read once and dropped — the cap bounds the total held, not the peak.
          if (bytes >= kMaxSnapshotBytes) {
            partial = true;
            break;
          }
          NSData* data = [item dataForType:type];
          if (!data) continue;
          bytes += data.length;
          if (bytes > kMaxSnapshotBytes) {
            partial = true;
            break;
          }
          [copy setData:data forType:type];
          wroteAny = true;
        }
        if (wroteAny) [copies addObject:copy];
      }
      if (partial) break;
    }
  } @catch (NSException* exception) {
    (void)exception;
    // Pasteboard owners are separate processes. AppKit reports provider communication failures as
    // Objective-C exceptions, which must not cross the N-API boundary into the host process.
    [copies removeAllObjects];
    partial = true;
  }

  Napi::Object result = Napi::Object::New(env);
  result.Set("token", Napi::String::New(env, PasteboardStash::Shared().Store(copies)));
  result.Set("changeCount", Napi::Number::New(env, static_cast<double>(pasteboard.changeCount)));
  result.Set("itemCount", Napi::Number::New(env, static_cast<double>(copies.count)));
  result.Set("partial", Napi::Boolean::New(env, partial));
  return result;
}

Napi::Value PasteboardRestore(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::String})) return Napi::Boolean::New(env, false);
  NSArray<NSPasteboardItem*>* items =
      PasteboardStash::Shared().Take(info[0].As<Napi::String>().Utf8Value());
  if (!items) return Napi::Boolean::New(env, false);
  NSPasteboard* pasteboard = [NSPasteboard generalPasteboard];
  bool restored = false;
  @try {
    [pasteboard clearContents];
    restored = items.count == 0 || [pasteboard writeObjects:items];
  } @catch (NSException* exception) {
    (void)exception;
    restored = false;
  }
  return Napi::Boolean::New(env, restored);
}

Napi::Value PasteboardDiscardSnapshot(const Napi::CallbackInfo& info) {
  if (!ArgsMatch(info, {ArgKind::String})) return info.Env().Undefined();
  PasteboardStash::Shared().Take(info[0].As<Napi::String>().Utf8Value());
  return info.Env().Undefined();
}

Napi::Value PasteboardWriteText(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::String})) {
    return Napi::Number::New(env, static_cast<double>([[NSPasteboard generalPasteboard] changeCount]));
  }
  NSPasteboard* pasteboard = [NSPasteboard generalPasteboard];
  [pasteboard clearContents];
  NSString* text = [NSString stringWithUTF8String:info[0].As<Napi::String>().Utf8Value().c_str()];
  if (text) {
    [pasteboard setString:text forType:NSPasteboardTypeString];
    // Declared alongside the text, never instead of it: a manager that ignores the markers still
    // finds a normal string, and the paste itself is unaffected.
    for (const char* type : kConcealmentTypes) {
      [pasteboard setData:[NSData data] forType:@(type)];
    }
    NSString* bundleId = [[NSBundle mainBundle] bundleIdentifier];
    if (bundleId) [pasteboard setString:bundleId forType:@(kPasteboardSourceType)];
  }
  return Napi::Number::New(env, static_cast<double>(pasteboard.changeCount));
}

Napi::Value ReleaseElement(const Napi::CallbackInfo& info) {
  if (!ArgsMatch(info, {ArgKind::String})) return info.Env().Undefined();
  ElementRegistry::Shared().Release(info[0].As<Napi::String>().Utf8Value());
  return info.Env().Undefined();
}


Napi::Object Init(Napi::Env env, Napi::Object exports) {
  exports.Set("isAccessibilityTrusted", Napi::Function::New(env, IsAccessibilityTrusted));
  exports.Set("isSecureInputEnabled", Napi::Function::New(env, IsSecureInputEnabled));
  exports.Set("secureInputCulprit", Napi::Function::New(env, SecureInputCulprit));
  exports.Set("currentModifierFlags", Napi::Function::New(env, CurrentModifierFlags));
  exports.Set("caretBounds", Napi::Function::New(env, CaretBounds));
  exports.Set("replaceRange", Napi::Function::New(env, ReplaceRange));
  exports.Set("confirmElement", Napi::Function::New(env, ConfirmElement));
  exports.Set("frontmostApp", Napi::Function::New(env, FrontmostApp));
  exports.Set("readFocusedElement", Napi::Function::New(env, ReadFocusedElement));
  exports.Set("readElementState", Napi::Function::New(env, ReadElementState));
  exports.Set("primeAccessibility", Napi::Function::New(env, PrimeAccessibility));
  exports.Set("verifyElement", Napi::Function::New(env, VerifyElement));
  exports.Set("setSelectedText", Napi::Function::New(env, SetSelectedText));
  exports.Set("setSelectedTextRange", Napi::Function::New(env, SetSelectedTextRange));
  exports.Set("casRangeEdit", Napi::Function::New(env, CasRangeEdit));
  exports.Set("setValue", Napi::Function::New(env, SetValue));
  exports.Set("postPaste", Napi::Function::New(env, PostPaste));
  exports.Set("postReturn", Napi::Function::New(env, PostReturn));
  exports.Set("postBackspace", Napi::Function::New(env, PostBackspace));
  exports.Set("typeUnicode", Napi::Function::New(env, TypeUnicode));
  exports.Set("pasteboardChangeCount", Napi::Function::New(env, PasteboardChangeCount));
  exports.Set("pasteboardSnapshot", Napi::Function::New(env, PasteboardSnapshot));
  exports.Set("pasteboardRestore", Napi::Function::New(env, PasteboardRestore));
  exports.Set("pasteboardDiscardSnapshot", Napi::Function::New(env, PasteboardDiscardSnapshot));
  exports.Set("pasteboardWriteText", Napi::Function::New(env, PasteboardWriteText));
  exports.Set("releaseElement", Napi::Function::New(env, ReleaseElement));
  return exports;
}

}  // namespace

NODE_API_MODULE(insertable, Init)
