#import "pasteboard.h"
#import "addon_state.h"
#import "napi_support.h"

#import <AppKit/AppKit.h>

namespace insertable {

namespace {

constexpr const char* kConcealmentTypes[] = {"org.nspasteboard.ConcealedType",
                                             "org.nspasteboard.TransientType",
                                             "org.nspasteboard.AutoGeneratedType"};

constexpr const char* kPasteboardSourceType = "org.nspasteboard.source";

constexpr NSUInteger kMaxSnapshotBytes = 16 * 1024 * 1024;

NSInteger CurrentChangeCount() {
  @try {
    return [[NSPasteboard generalPasteboard] changeCount];
  } @catch (NSException* exception) {
    (void)exception;
    return 0;
  }
}

}  // namespace

Napi::Value PasteboardChangeCount(const Napi::CallbackInfo& info) {
  return Napi::Number::New(info.Env(), static_cast<double>(CurrentChangeCount()));
}

/**
 * Copies every flavor of every pasteboard item out of the pasteboard and stashes it natively.
 * The contents never enter the JavaScript heap — the caller gets an opaque token.
 */
Napi::Value PasteboardSnapshot(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  NSPasteboard* pasteboard = [NSPasteboard generalPasteboard];
  NSMutableArray<NSPasteboardItem*>* copies = [NSMutableArray array];
  NSUInteger bytes = 0;
  bool partial = false;

  @try {
    // The per-flavor NSData reads can be large; drain them per item rather than holding every
    // temporary until the next run-loop turn.
    for (NSPasteboardItem* item in pasteboard.pasteboardItems) {
      @autoreleasepool {
        NSPasteboardItem* copy = [[NSPasteboardItem alloc] init];
        bool wroteAny = false;
        for (NSPasteboardType type in item.types) {
          // Checked before the read, not after: NSPasteboardItem cannot report a flavor's size
          // without materializing it, so the budget can only stop the NEXT copy. One oversized
          // flavor is still read once and dropped — the cap bounds the total held, not the peak.
          if (bytes >= kMaxSnapshotBytes) {
            partial = true;
            break;
          }
          NSData* data = [item dataForType:type];
          if (!data) continue;
          bytes += data.length;
          if (bytes > kMaxSnapshotBytes) {
            partial = true;
            break;
          }
          [copy setData:data forType:type];
          wroteAny = true;
        }
        if (wroteAny) [copies addObject:copy];
      }
      if (partial) break;
    }
  } @catch (NSException* exception) {
    (void)exception;
    // Pasteboard owners are separate processes. AppKit reports provider communication failures as
    // Objective-C exceptions, which must not cross the N-API boundary into the host process.
    [copies removeAllObjects];
    partial = true;
  }

  Napi::Object result = Napi::Object::New(env);
  result.Set("token", Napi::String::New(env, StateFrom(info)->pasteboard.Store(copies)));
  result.Set("changeCount", Napi::Number::New(env, static_cast<double>(CurrentChangeCount())));
  result.Set("itemCount", Napi::Number::New(env, static_cast<double>(copies.count)));
  result.Set("partial", Napi::Boolean::New(env, partial));
  return result;
}

Napi::Value PasteboardRestore(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::String})) return Napi::Boolean::New(env, false);
  NSArray<NSPasteboardItem*>* items =
      StateFrom(info)->pasteboard.Take(info[0].As<Napi::String>().Utf8Value());
  if (!items) return Napi::Boolean::New(env, false);
  bool restored = false;
  @try {
    NSPasteboard* pasteboard = [NSPasteboard generalPasteboard];
    [pasteboard clearContents];
    restored = items.count == 0 || [pasteboard writeObjects:items];
  } @catch (NSException* exception) {
    (void)exception;
    restored = false;
  }
  return Napi::Boolean::New(env, restored);
}

Napi::Value PasteboardDiscardSnapshot(const Napi::CallbackInfo& info) {
  if (!ArgsMatch(info, {ArgKind::String})) return info.Env().Undefined();
  StateFrom(info)->pasteboard.Take(info[0].As<Napi::String>().Utf8Value());
  return info.Env().Undefined();
}

Napi::Value PasteboardWriteText(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (!ArgsMatch(info, {ArgKind::String})) {
    return Napi::Number::New(env, static_cast<double>(CurrentChangeCount()));
  }
  @try {
    NSPasteboard* pasteboard = [NSPasteboard generalPasteboard];
    [pasteboard clearContents];
    NSString* text = [NSString stringWithUTF8String:info[0].As<Napi::String>().Utf8Value().c_str()];
    if (text) {
      [pasteboard setString:text forType:NSPasteboardTypeString];
      // Declared alongside the text, never instead of it: a manager that ignores the markers
      // still finds a normal string, and the paste itself is unaffected.
      for (const char* type : kConcealmentTypes) {
        [pasteboard setData:[NSData data] forType:@(type)];
      }
      NSString* bundleId = [[NSBundle mainBundle] bundleIdentifier];
      if (bundleId) [pasteboard setString:bundleId forType:@(kPasteboardSourceType)];
    }
    return Napi::Number::New(env, static_cast<double>(pasteboard.changeCount));
  } @catch (NSException* exception) {
    (void)exception;
    return Napi::Number::New(env, static_cast<double>(CurrentChangeCount()));
  }
}

}  // namespace insertable
